# DUA environment container management settings.
#
# Roberto Masocco <r.masocco@dotxautomation.com>
#
# March 9, 2026

# Copyright 2026 dotX Automation s.r.l.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:  
  builder:
    build:
      context: /home/labadmin
      network: host
      dockerfile: ./dua-template/docker/container-x86-cudev/Dockerfile
      args:
        # Standardize this to 1000 for the 'Gold Image'
        # Distrobox will override this anyway at runtime
        - USER_UID=1000 
    image: cearlab_dev_nvidia:x86-cudev